name: Version Tagging

on:
  push:
    branches:
      - 'feature/**'

jobs:
  create-tag:
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, 'create tag')
    permissions:
      contents: write

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      # Step 2: Extract Version from Readme.txt
      - name: Extract Version from Readme
        id: extract_version
        run: |
          README_PATH="trunk/readme.md"

          # Check if the readme file exists
          if [ ! -f "$README_PATH" ]; then
            echo "Error: Readme file not found at $README_PATH. Exiting."
            exit 1
          fi

          # Extract the version number from the readme file
          VERSION_LINE=$(grep -i "^Version:" "$README_PATH" || true)

          if [[ "$VERSION_LINE" =~ ^Version:\ ([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            VERSION="${BASH_REMATCH[1]}"
            echo "Extracted version: $VERSION"
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          else
            echo "Error: No valid version number found in the readme file. Exiting."
            exit 1
          fi

      # Step 3: Check if the Tag Folder Already Exists
      - name: Check if Tag Folder Exists
        run: |
          echo "Creating tag folder tags/${{ env.VERSION }}."
          mkdir -p tags/${{ env.VERSION }}

      # Step 4: Create Tag Folder and Copy Files
      - name: Copy Files to Tag Folder
        run: |
          rsync -av --exclude='tags' --exclude='.git' --exclude='.github' ./ tags/${{ env.VERSION }}/
          ls -R tags/${{ env.VERSION }}/

      # Step 5: Configure Git User
      - name: Configure Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Step 6: Commit and Push Tag Folder
      - name: Commit and Push Tag Folder
        run: |
          git add tags/
          git commit -m "Create tag folder v${{ env.VERSION }} from commit $GITHUB_SHA"
          git push origin ${{ github.ref }}