name: Tag and Deploy

on:
  push:
    branches:
      - master

jobs:
  tag-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      # Step 2: Extract Version from Readme.txt
      - name: Extract Version from Readme
        id: extract_version
        run: |
          README_PATH="trunk/readme.md"

          # Check if the readme file exists
          if [ ! -f "$README_PATH" ]; then
            echo "Error: Readme file not found at $README_PATH. Exiting."
            exit 1
          fi

          # Extract the version number from the readme file
          VERSION_LINE=$(grep -i "^Version:" "$README_PATH" || true)

          if [[ "$VERSION_LINE" =~ ^Version:\ ([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            VERSION="${BASH_REMATCH[1]}"
            echo "Extracted version: $VERSION"
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          else
            echo "Error: No valid version number found in the readme file. Exiting."
            exit 1
          fi

      # Step 4: Check if the Tag Folder Already Exists
      - name: Check if Tag Folder Exists
        run: |
            echo "Creating tag folder tags/${{ env.VERSION }}."
            mkdir -p tags/${{ env.VERSION }}

      # Step 5: Create Tag Folder and Copy Files
      - name: Copy Files to Tag Folder
        run: |
          rsync -av --exclude='tags' --exclude='.git' --exclude='.github' ./ tags/${{ env.VERSION }}/
          ls -R tags/${{ env.VERSION }}/

      - name: Configure Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Step 6: Commit and Push Tag Folder
      - name: Commit and Push Tag Folder
        run: |
          git add tags/
          git commit -m "Create tag folder v${{ env.VERSION }} from commit $GITHUB_SHA"
          git push origin master

      # Step 7: Install SVN
      - name: Install SVN
        run: |
          sudo apt-get update
          sudo apt-get install -y subversion

      # Step 8: Checkout SVN Repository
      - name: Checkout SVN Repository
        run: |
          svn checkout --username "${{ secrets.WORDPRESS_SVN_USERNAME }}" --password "${{ secrets.WORDPRESS_SVN_PASSWORD }}" "$SVN_REPO_URL" svn-repo
        env:
          SVN_REPO_URL: https://svn.riouxsvn.com/ikhokha-payment

      # Step 9: Sync Folders to SVN
      - name: Sync Folders to SVN
        run: |
          rsync -av --delete ./trunk/ svn-repo/trunk/
          rsync -av --delete ./assets/ svn-repo/assets/
          rsync -av --delete ./tags/ svn-repo/tags/

      # Step 10: Add New Files to SVN
      - name: Add New Files to SVN
        run: |
          cd svn-repo
          svn add --force * --auto-props --parents --depth infinity -q

      # Step 11: Commit Changes to SVN
      - name: Commit Changes to SVN
        run: |
          cd svn-repo
          svn commit -m "Deploy trunk, assets, and tags from Git commit $GITHUB_SHA" --username "${{ secrets.WORDPRESS_SVN_USERNAME }}" --password "${{ secrets.WORDPRESS_SVN_PASSWORD }}" --no-auth-cache --non-interactive
