name: Deploy to SVN

on:
  push:
    branches:
      - master

jobs:
  deploy-svn:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install SVN
        run: |
          sudo apt-get update
          sudo apt-get install -y subversion

      - name: Checkout SVN Repository
        run: |
          svn checkout --username "${{ secrets.WORDPRESS_SVN_USERNAME }}" --password "${{ secrets.WORDPRESS_SVN_PASSWORD }}" "$SVN_REPO_URL" svn-repo
        env:
          SVN_REPO_URL: https://svn.riouxsvn.com/ikhokha-payment

      - name: Sync Folders to SVN
        run: |
          rsync -av --delete ./trunk/ svn-repo/trunk/
          rsync -av --delete ./assets/ svn-repo/assets/
          rsync -av --delete ./tags/ svn-repo/tags/

      - name: Add New Files to SVN
        run: |
          cd svn-repo
          svn add --force * --auto-props --parents --depth infinity -q

      - name: Commit Changes to SVN
        run: |
          cd svn-repo
          svn commit -m "Deploy trunk, assets, and tags from Git commit $GITHUB_SHA" --username "${{ secrets.WORDPRESS_SVN_USERNAME }}" --password "${{ secrets.WORDPRESS_SVN_PASSWORD }}" --no-auth-cache --non-interactive
