name: Deploy to SVN

on:
  push:
    branches:
      - master  # Trigger on pushes to the master branch

jobs:
  deploy-svn:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history

      - name: Install SVN
        run: |
          sudo apt-get update
          sudo apt-get install -y subversion

      - name: Checkout SVN Repository
        run: |
          svn checkout --username "$SVN_USERNAME" --password "$SVN_PASSWORD" "$SVN_REPO_URL" svn-repo
        env:
          SVN_USERNAME: ${{ secrets.WORDPRESS_SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.WORDPRESS_SVN_PASSWORD }}
          SVN_REPO_URL: https://svn.riouxsvn.com/melowing

      - name: Sync Folders to SVN
        run: |
          # Define source and destination paths
          SRC_TRUNK="./trunk/"
          SRC_ASSETS="./assets/"
          SRC_TAGS="./tags/"
          DST_TRUNK="svn-repo/trunk/"
          DST_ASSETS="svn-repo/assets/"
          DST_TAGS="svn-repo/tags/"

          # Sync trunk
          rsync -av --delete "$SRC_TRUNK" "$DST_TRUNK"

          # Sync assets
          rsync -av --delete "$SRC_ASSETS" "$DST_ASSETS"

          # Sync tags
          rsync -av --delete "$SRC_TAGS" "$DST_TAGS"

      - name: Add New Files to SVN
        run: |
          cd svn-repo
          svn add --force * --auto-props --parents --depth infinity -q

      - name: Commit Changes to SVN
        run: |
          cd svn-repo
          svn commit -m "Deploy trunk, assets, and tags from Git commit $GITHUB_SHA" --username "$SVN_USERNAME" --password "$SVN_PASSWORD" --no-auth-cache --non-interactive
        env:
          SVN_USERNAME: ${{ secrets.WORDPRESS_SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.WORDPRESS_SVN_PASSWORD }}
