name: Create Tag and Deploy to SVN

on:
  push:
    branches:
      - master

jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write



    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          persist-credentials: true

      - name: Run Create Tag Script
        run: ./scripts/create_tag.sh
        env:
          GITHUB_SHA: ${{ github.sha }}

  publish-plugin:
    needs: create-tag
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Deploy SVN Script
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          VERSION: ${{ env.VERSION }}
          GITHUB_SHA: ${{ github.sha }}
        run: ./scripts/publish_plugin.sh
