name: Tag and Deploy

on:
  push:
    branches:
      - master

jobs:
  tag-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      # Step 2: Run Version Tagging Script
      - name: Run Version Tagging Script
        run: ./.github/scripts/version_tag.sh

      # Step 3: Run Deployment Script
      - name: Run Deployment Script
        run: ./.github/scripts/deploy.sh
        env:
          SVN_USERNAME: ${{ secrets.WORDPRESS_SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.WORDPRESS_SVN_PASSWORD }}
          SVN_REPO_URL: https://svn.riouxsvn.com/ikhokha-payment
